send_email: 
  handler: ./apis/send_email/handler
  endpoint: /send_email
  method: get
  enabled: true
  #UNCOMMENT TO ATTACH MIDDLEWARE
  #EXAMPLE: middleware: middleware
  #middleware: <middleware_name>
